export const SELECT_SEARCH_LIST_ITEM = 'SELECT_SEARCH_LIST_ITEM';
export const SET_PROPERTY_LIST = 'SET_PROPERTY_LIST';
export const SET_DIRECTION = 'SET_DIRECTION';
export const SET_POLYGON = 'SET_POLYGON';
